---
- name: Configure Docker on Deployserver
  hosts: all
  become: true

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3-pip
          - docker.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Python module
      pip:
        name: docker

    - name: Pull Docker image from DockerHub
      community.docker.docker_image:
        name: aniirudh/insure-meproject:latest
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: insure-me
        image: aniirudh/insure-meproject:latest
        state: started
        restart_policy: always
        published_ports:
          - "8080:8081"
